# Generated by Django 3.1 on 2020-08-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.CharField(default='https://cdn.patch.com/assets/contrib/images/placeholder-user-photo.png', max_length=500),
        ),
    ]
